export const GET_USER_LOGEG = "GET_USER_LOGEG";
export const CLOSE_SESION = "CLOSE_SESION";

// here the fancy export code to storage the info to edit
export const GET_SUPPLIER_TO_EDIT = "GET_SUPPLIER_TO_EDIT";
export const GET_CUSTOMER_TO_EDIT = "GET_CUSTOMER_TO_EDIT";
export const GET_PRODUCT_TO_EDIT = "GET_PRODUCT_TO_EDIT";

export const GET_LIST_PRODUCTS_TO_DELIVER = "GET_LIST_PRODUCTS_TO_DELIVER";

export const GET_CUSTOMER_INFO = "GET_CUSTOMER_INFO";

export const GET_CANTIDAD_DESPACHADA = "GET_CANTIDAD_DESPACHADA";
export const GET_CUSTOMER_ADDPRODUCT = "GET_CUSTOMER_ADDPRODUCT";
export const GET_TOTAL_AMOUNT = "GET_TOTAL_AMOUNT";
